# Interval in Minecraft ticks for checking player inventories. Possible values: any integer. Default: 3600 (2 minutes and 30 seconds).
inventory_check_interval = 3600

# Determines if items are consumed on successful spawns. Possible values: true, false. Default: false.
consume_items_on_successful_spawn = false

# If true, and both a key item and item condition are set, only items are consumed. Possible values: true, false. Default: true.
ignore_key_items = true

# List of loot tables where key items can appear. These tables are modified to include key items.
loot_tables = [
  "minecraft:chests/abandoned_mineshaft",
  "minecraft:chests/ancient_city",
  "minecraft:chests/bastion_treasure",
  "minecraft:chests/buried_treasure",
  "minecraft:chests/desert_pyramid",
  "minecraft:chests/end_city_treasure",
  "minecraft:chests/jungle_temple",
  "minecraft:chests/shipwreck_treasure",
  "minecraft:chests/woodland_mansion",
  "minecraft:gameplay/fishing/treasure",
  "minecraft:gameplay/sniffer_digging",
  "minecraft:archaeology/trail_ruins_rare"
]

# The chance for items added to the loot tables to spawn. Possible values: any float. Default: 0.005.
loot_table_item_spawn_chance = 0.005

# If true, the spawn chance is divided by the total number of key items (currently 30), balancing their appearance. Possible values: true, false. Default: false.
divide_item_spawn_chance = false

# List of items to be checked in the inventory at each interval.
inventory_check_item_list = [
  "minecraft:diamond",
  "minecraft:emerald",
  "minecraft:nether_star",
  "cobblemon:dragon_scale",
  "cobblemon:electirizer",
  "cobblemon:magmarizer",
  "cobblemon:metal_coat",
  "cobblemon:protector",
  "cobblemon:leaf_stone",
  "cobblemon:moon_stone",
  "cobblemon:sun_stone",
  "cobblemon:shiny_stone",
  "cobblemon:dusk_stone",
  "cobblemon:dawn_stone",
  "cobblemon:ice_stone",
  "cobblemon:thunder_stone",
  "cobblemon:fire_stone",
  "cobblemon:water_stone",
  "cobblemon:never_melt_ice"
]
